# Generated by Django 3.2.6 on 2021-11-27 05:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afternoon_Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(default='', max_length=50)),
                ('Available', models.CharField(default='', max_length=10)),
                ('When', models.CharField(default='Lunch', max_length=30, verbose_name='Lunch')),
            ],
        ),
        migrations.CreateModel(
            name='All_Meal_Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Hostel', models.CharField(default=1, max_length=13)),
                ('Food_Name', models.CharField(default='', max_length=50)),
                ('Food_ID', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(default='', max_length=50)),
                ('Quantity', models.CharField(default='', max_length=10)),
                ('Date_Time', models.CharField(default='', max_length=50)),
                ('When', models.CharField(default='breakfast', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Roll', models.CharField(default='', max_length=50)),
                ('Hostel', models.CharField(default=1, max_length=13)),
                ('Room_Number', models.CharField(default='', max_length=13)),
                ('Break_qun', models.IntegerField(default=0, max_length=50)),
                ('Break', models.CharField(default='', max_length=50)),
                ('Break_price', models.IntegerField(default=0, max_length=50)),
                ('Lunch_qun', models.IntegerField(default=0, max_length=50)),
                ('Lunch', models.CharField(default='', max_length=50)),
                ('Lunch_price', models.IntegerField(default=0, max_length=50)),
                ('Denar_qun', models.IntegerField(default=0, max_length=50)),
                ('Denar', models.CharField(default='', max_length=50)),
                ('Denar_price', models.IntegerField(default=0, max_length=50)),
                ('Date_Time', models.CharField(default=datetime.date(2021, 11, 27), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Denar_Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(default='', max_length=50)),
                ('Available', models.CharField(default='', max_length=10)),
                ('When', models.CharField(default='Dinner', max_length=30, verbose_name='Dinner')),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Roll', models.CharField(default='', max_length=50)),
                ('Hostel', models.CharField(default=1, max_length=13)),
                ('Room_Number', models.CharField(default='', max_length=13)),
                ('Food_Name', models.CharField(default='', max_length=50)),
                ('Food_ID', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(default='', max_length=50)),
                ('Quantity', models.CharField(default='', max_length=10)),
                ('Date_Time', models.CharField(default='', max_length=50)),
                ('When', models.CharField(default='Breakfast', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Morning_Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(default='', max_length=50)),
                ('Available', models.CharField(default='', max_length=10)),
                ('When', models.CharField(default='Breakfast', max_length=30, verbose_name='Breakfast')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('Athor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Titel', models.CharField(default='', max_length=50)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Amount', models.IntegerField(max_length=50)),
                ('Date', models.DateField(default=datetime.date(2021, 11, 27))),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUpdate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('StudentName', models.CharField(default='', max_length=100)),
                ('Hostel', models.CharField(default=1, max_length=13)),
                ('Image', models.ImageField(default='static/profile/avatar.png', upload_to='static/profile/pic/')),
                ('Numer', models.TextField(default='Enter Phone Number')),
                ('Room_Number', models.CharField(default='00', max_length=10)),
                ('Father_name', models.CharField(default='Need to Enter', max_length=50)),
                ('Father_profession', models.CharField(default='Need to Enter', max_length=100)),
                ('Class_Roll', models.CharField(default='Need to Enter', max_length=50)),
                ('Bed_Number', models.CharField(default='00', max_length=10)),
                ('Blood_Group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O+', 'O+'), ('O-', 'O-')], default='+-', max_length=5)),
                ('Address', models.CharField(default='Need to Enter', max_length=300)),
                ('Parents_number', models.CharField(default='Need to Enter', max_length=15)),
                ('Date_of_Birth', models.CharField(default='Need to Enter', max_length=30)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=10)),
                ('Emediate_Gauedion_Numer', models.CharField(default='Need to Enter', max_length=15)),
                ('MealBill', models.CharField(default='000', max_length=10)),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
    ]
