# Generated by Django 3.2.6 on 2021-09-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afternoon_Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(default='', max_length=50)),
                ('Available', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Denar_Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(default='', max_length=50)),
                ('Available', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Food_Name', models.CharField(default='', max_length=50)),
                ('Food_ID', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(default='', max_length=50)),
                ('Quantity', models.CharField(default='', max_length=10)),
                ('Date_Time', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Morning_Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(default='', max_length=50)),
                ('Available', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUpdate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Image', models.ImageField(default='static/profile/avatar.png', upload_to='static/profile/pic/')),
                ('Numer', models.TextField(default='Enter Phone Number')),
                ('Room_Number', models.CharField(default='00', max_length=10)),
                ('Father_name', models.CharField(default='Need to Enter', max_length=50)),
                ('Class_Roll', models.CharField(default='Need to Enter', max_length=50)),
                ('Bed_Number', models.CharField(default='00', max_length=10)),
                ('Blord_Group', models.CharField(default='+-', max_length=2)),
                ('Address', models.CharField(default='Need to Enter', max_length=300)),
                ('Parents_number', models.CharField(default='Need to Enter', max_length=15)),
                ('Date_of_Barth', models.CharField(default='Need to Enter', max_length=30)),
                ('Gender', models.CharField(default='Need to Enter', max_length=13)),
                ('Emediate_Gauedion_Numer', models.CharField(default='Need to Enter', max_length=15)),
                ('MealBill', models.CharField(default='000', max_length=10)),
            ],
        ),
    ]
