# Generated by Django 3.2.6 on 2021-11-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilupdate',
            name='Class_Roll',
            field=models.CharField(default='Need to Enter', max_length=50, unique=True),
        ),
    ]
