# Generated by Django 3.2.6 on 2021-09-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Meal_Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Food_Name', models.CharField(default='', max_length=50)),
                ('Food_ID', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(default='', max_length=50)),
                ('Quantity', models.CharField(default='', max_length=10)),
                ('Date_Time', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
