# Generated by Django 3.2.6 on 2021-09-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0002_all_meal_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilupdate',
            name='Hostel',
            field=models.CharField(default=1, max_length=13),
        ),
    ]
