# Generated by Django 3.2.6 on 2021-11-27 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0002_alter_profilupdate_class_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 11, 27)),
        ),
    ]
