# Generated by Django 3.2.6 on 2021-09-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0003_profilupdate_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_order',
            name='Hostel',
            field=models.CharField(default=1, max_length=13),
        ),
    ]
