# Generated by Django 3.2.6 on 2021-11-28 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0004_auto_20211127_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_history',
            old_name='Fixed_Food',
            new_name='Development',
        ),
        migrations.RenameField(
            model_name='payment_history',
            old_name='Ledge_Development',
            new_name='Fixed',
        ),
        migrations.AddField(
            model_name='payment_history',
            name='Food',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='payment_history',
            name='Pledge',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='demo',
            name='Date_Time',
            field=models.CharField(default=datetime.date(2021, 11, 28), max_length=50),
        ),
        migrations.AlterField(
            model_name='notice',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 11, 28)),
        ),
        migrations.AlterField(
            model_name='payment_history',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 11, 28)),
        ),
        migrations.AlterField(
            model_name='profilupdate',
            name='Numer',
            field=models.IntegerField(default=880),
        ),
    ]
