# Generated by Django 3.2.6 on 2021-09-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0005_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilupdate',
            name='permission',
            field=models.CharField(default='no', max_length=5),
        ),
    ]
