# Generated by Django 3.2.6 on 2021-09-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0006_profilupdate_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_order',
            name='When',
            field=models.CharField(default='breakfast', max_length=30),
        ),
    ]
