# Generated by Django 3.2.6 on 2021-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0008_auto_20210929_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_meal_order',
            name='Hostel',
            field=models.CharField(default=1, max_length=13),
        ),
        migrations.AddField(
            model_name='all_meal_order',
            name='When',
            field=models.CharField(default='breakfast', max_length=30),
        ),
    ]
