# Generated by Django 3.2.6 on 2021-09-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0011_auto_20210929_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilupdate',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Need to Enter', max_length=50),
        ),
    ]
