# Generated by Django 3.2.6 on 2021-09-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0012_alter_profilupdate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilupdate',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=50),
        ),
    ]
