# Generated by Django 3.2.6 on 2021-09-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0013_alter_profilupdate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilupdate',
            name='Blord_Group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+')], default='+-', max_length=5),
        ),
        migrations.AlterField(
            model_name='profilupdate',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=10),
        ),
    ]
