# Generated by Django 3.2.6 on 2021-09-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0014_auto_20210929_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_order',
            name='When',
            field=models.CharField(default='Breakfast', max_length=30),
        ),
        migrations.AlterField(
            model_name='morning_meal',
            name='When',
            field=models.CharField(default='breakfast', max_length=30, verbose_name='Breakfast'),
        ),
    ]
