# Generated by Django 3.2.6 on 2021-10-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0015_auto_20210929_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilupdate',
            name='Blord_Group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O+', 'O+'), ('O-', 'O-')], default='+-', max_length=5),
        ),
    ]
