# Generated by Django 3.2.6 on 2021-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0016_alter_profilupdate_blord_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilupdate',
            name='Blord_Group',
        ),
        migrations.RemoveField(
            model_name='profilupdate',
            name='Date_of_Barth',
        ),
        migrations.AddField(
            model_name='profilupdate',
            name='Date_of_Birth',
            field=models.CharField(default='Need to Enter', max_length=30),
        ),
    ]
