# Generated by Django 3.2.6 on 2021-10-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mist', '0017_auto_20211002_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilupdate',
            name='Blood_Group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O+', 'O+'), ('O-', 'O-')], default='+-', max_length=5),
        ),
    ]
